title: "Disruptive Technologies: MMS 142 Group N"
page-top-title: "MMS 142 Group N"
top-section-bg-text: "Group Activity: Disruptive Technologies"
home-subtitle: "Cryptocurrency as a Disruptor of Traditional Finance Systems"
copyright: "2024 Group N. All rights reserved."